on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Release Job
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16 ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags}" >> $GITHUB_ENV
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Build Project
        run: |
          npm install
          npm run build
          zip touch-vtt.zip module.json dist/* lang/* templates/*
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            module.json
            touch-vtt.zip